### ISSUE TITLE
OSError: [E053] Could not read config.cfg from .....\venv\lib\site-packages\pyresparser\config.cfg

### ISSUE THREAD

**Issue by MinaTahaei** [OmkarPathak/pyresparser#46]
I have installed all the packages, but when I run:

`from pyresparser import ResumeParser
data = ResumeParser('C:/Users/Asus/Desktop/ResumeParserExample/test.pdf').get_extracted_data()`

I get this error:

`C:\Users\Asus\Desktop\ResumeParserExample\venv\lib\site-packages\spacy\util.py:715: UserWarning: [W094] Model 'en_training' (0.0.0) specifies an under-constrained spaCy version requirement: >=2.1.4. This can lead to compatibility problems with older versions, or as new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.0.1,<3.1.0
  warnings.warn(warn_msg)`

`OSError: [E053] Could not read config.cfg from C:\Users\Asus\Desktop\ResumeParserExample\venv\lib\site-packages\pyresparser\config.cfg`

Does anyone know what the problem is?

Edit: looks like config.cfg doesn't get created at all

**Comment by tanvidadu** [comment]
Facing similar issue

**Comment by Sandeep-Panchal** [comment]
I am too facing the similar issue.

**Comment by Bhavin1996** [comment]
same issue

**Comment by cristinabac** [comment]
Same issue

**Comment by Quppi** [comment]
Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue:
`pip install nltk
pip install spacy==2.3.5
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
pip install pyresparser`
does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

**Comment by cristinabac** [comment]
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue:
> `pip install nltk`
> `pip install spacy==2.3.5`
> `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz`
> `pip install pyresparser`
> does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

This worked for me, thank you!

**Comment by MinaTahaei** [comment]
> pip install pyresparser

Unfortunately I still have a version issue: C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
  
  but then when I want to install an older spaCy version, I get errors that the packs don't exist

**Comment by MinaTahaei** [comment]
> 
> 
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue:
> `pip install nltk`
> `pip install spacy==2.3.5`
> `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz`
> `pip install pyresparser`
> does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

Unfortunately I still have a version issue: C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_training' (0.0.0) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
warnings.warn(warn_msg)

but then when I want to install an older spaCy version, I get errors that the packs don't exist

**Comment by Quppi** [comment]
Hmh, I get the same warning message, though after that I get the output of the parsed resume.

**Comment by MinaTahaei** [comment]
> 
> 
> Hmh, I get the same warning message, though after that I get the output of the parsed resume.

Where do you get the output of the parsed resume? Does it get rewritten in a new file, or it appears in the terminal?(because I have nothing in my terminal)

**Comment by Quppi** [comment]
It's right after the warning message in the terminal. But you might want to add a 
`print(data)`
at the end of the script given in the Readme :)

**Comment by MinaTahaei** [comment]
> print(data)

Damn, I had forgotten that:))   Thanks, its fixed now!:))

**Comment by MinaTahaei** [comment]
> 
> 
> It's right after the warning message in the terminal. But you might want to add a
> `print(data)`
> at the end of the script given in the Readme :)

Damn, I had forgotten that:)) Thanks, its fixed now!:))

**Comment by RAravindDS** [comment]
When I try to run pip install spacy==2.3.5 I got some other error. 

WARNING: Discarding https://files.pythonhosted.org/packages/45/71/507b8dbbe3ee6f93c0356c3e5e902e0f598c02d919ad3116e16559eb011f/spacy-2.3.5.tar.gz#sha256=315278ab60094643baecd866017c7d4cbd966efd2d517ad0e6c888edf7fa5aef (from https://pypi.org/simple/spacy/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7). Command errored out with exit status 1: 'C:\Users\aravi\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\aravi\AppData\Local\Temp\pip-standalone-pip-3tor27n0\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\aravi\AppData\Local\Temp\pip-build-env-1a___yu5\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.4.1,<7.5.0' 'blis>=0.4.0,<0.8.0' 'numpy>=1.15.0' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement spacy==2.3.5 (from versions: 0.31, 0.32, 0.33, 0.40, 0.51, 0.52, 0.60, 0.61, 0.62, 0.63, 0.64, 0.65, 0.67, 0.68, 0.70, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.97, 0.98, 0.99, 0.100.0, 0.100.1, 0.100.2, 0.100.3, 0.100.4, 0.100.5, 0.100.6, 0.100.7, 0.101.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.5, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.10.0, 1.10.1, 2.0.0, 2.0.1.dev0, 2.0.1, 2.0.2.dev0, 2.0.2, 2.0.3.dev0, 2.0.3, 2.0.4.dev0, 2.0.4, 2.0.5.dev0, 2.0.5, 2.0.6.dev0, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10.dev0, 2.0.10, 2.0.11.dev0, 2.0.11, 2.0.12.dev0, 2.0.12.dev1, 2.0.12, 2.0.13.dev0, 2.0.13.dev1, 2.0.13.dev2, 2.0.13.dev4, 2.0.13, 2.0.14.dev0, 2.0.14.dev1, 2.0.15, 2.0.16.dev0, 2.0.16, 2.0.17.dev0, 2.0.17.dev1, 2.0.17, 2.0.18.dev0, 2.0.18.dev1, 2.0.18, 2.1.0, 2.1.1.dev0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7.dev0, 2.1.7, 2.1.8, 2.1.9, 2.2.0.dev10, 2.2.0.dev11, 2.2.0.dev13, 2.2.0.dev15, 2.2.0.dev17, 2.2.0.dev18, 2.2.0.dev19, 2.2.0, 2.2.1, 2.2.2.dev0, 2.2.2.dev4, 2.2.2, 2.2.3.dev0, 2.2.3, 2.2.4, 2.3.0.dev1, 2.3.0, 2.3.1, 2.3.2, 2.3.3.dev0, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 3.0.0, 3.0.1.dev0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.2, 3.2.3)
ERROR: No matching distribution found for spacy==2.3.5

**Comment by johncarlo-vss** [comment]
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue: `pip install nltk` `pip install spacy==2.3.5` `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz` `pip install pyresparser` does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

Bro. What version of Python did you use?

**Comment by RAravindDS** [comment]
Guys, I have many thing for this. But I can't solve my issues, one way to solve this: 

https://www.programcreek.com/python/?code=OmkarPathak%2FResumeParser%2FResumeParser-master%2Fresume_parser%2Fresume_parser%2Fresume_parser.py#

Go here, and copy paste the entire code in your respective folder and try to solve the problem. I have done this for my company and if you do this there are lot of flexibility is there, you can solve name issues, skill issue based on your company requirements, it helped me a lot, and Now I have a very good resume parser for my specific domain. I took time but this will help to get a good model  Guys!. 

Hope I helped you 💔

**Comment by zeinramadan1** [comment]
I was still having this issue and could not solve it but finally did. The problem for me was my machine, it's a mac with the new chip. Pretty sure this library will not work on this device. Got it working on WSL in windows though. Hope this helps anybody stuck with this error. I was stuck for a good 2 weeks.

**Comment by Amit3729** [comment]
Still I got a error as it show:  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for spacy
Failed to build spacy
ERROR: Could not build wheels for spacy, which is required to install pyproject.toml-based projects

**Comment by yash22y** [comment]
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue: `pip install nltk` `pip install spacy==2.3.5` `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz` `pip install pyresparser` does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

thank you soo much you are a real saver :)

**Comment by hvt77** [comment]
Thanks a lot @Quppi, that was really helpful.

I managed to get pyresparser working on python 3.10 (google collaboration notebook) and 3.11 (local laptop), by installing spacy 2.3.9 and en core web sm 2.3.1.

While trying to install spacy 2.3.5, it was giving an error of missing wheel file, thanks to this stackexchange article (https://stackoverflow.com/questions/68651829/how-to-install-specific-version-of-spacy), I gave "pip install spacy ~= 2.3.5" (instead of "pip install spacy ==2.3.5").

Rest of the instructions worked as is from @Quppi 's solution!

Ps: i must comment: results of resume parsing weren't too great (messed up extracting total experience in all resumes,  some names, emails and mobile numbers too were incorrect or missing), so not sure if it really needs spacy 2.3.5 to work better.

Any way we can install 2.3.5 on latest py versions? Or on which py version can we get spacy 2.3.5 and ecws 2.3.1 working even today?!

**Comment by kumarme072** [comment]
> Thanks a lot @Quppi, that was really helpful.
> 
> I managed to get pyresparser working on python 3.10 (google collaboration notebook) and 3.11 (local laptop), by installing spacy 2.3.9 and en core web sm 2.3.1.
> 
> While trying to install spacy 2.3.5, it was giving an error of missing wheel file, thanks to this stackexchange article (https://stackoverflow.com/questions/68651829/how-to-install-specific-version-of-spacy), I gave "pip install spacy ~= 2.3.5" (instead of "pip install spacy ==2.3.5").
> 
> Rest of the instructions worked as is from @Quppi 's solution!
> 
> Ps: i must comment: results of resume parsing weren't too great (messed up extracting total experience in all resumes, some names, emails and mobile numbers too were incorrect or missing), so not sure if it really needs spacy 2.3.5 to work better.
> 
> Any way we can install 2.3.5 on latest py versions? Or on which py version can we get spacy 2.3.5 and ecws 2.3.1 working even today?!

pip install "spacy ~= 2.3.5"

**Comment by Kuljeet-1993** [comment]
![parsing_error](https://github.com/OmkarPathak/pyresparser/assets/79419695/852a2960-9c43-4393-ab29-f7918df96e43)
I have run complete code but unable to see output. Please refer to screenshot attached

**Comment by royaad** [comment]
@hvt77 can you share your colab notebook? at least with the installation. I am still having an error with pyresparser.

**Comment by royaad** [comment]
I finally managed to make it work after following @hvt77 's instructions. I still got some warnings but no errors. However, the parser performed really bad for extracting the total experience. Does anyone have similar issues when it comes to the accuracy of the parser? I also tried resume-parser same issue as pyresparser.

**Comment by Malek-O** [comment]
> I finally managed to make it work after following @hvt77 's instructions. I still got some warnings but no errors. However, the parser performed really bad for extracting the total experience. Does anyone have similar issues when it comes to the accuracy of the parser? I also tried resume-parser same issue as pyresparser. Anyone has experience with better parsers?


did you find any solution to the accuracy of the parser?

**Comment by nadershehata95** [comment]
> Thanks a lot @Quppi, that was really helpful.
> 
> I managed to get pyresparser working on python 3.10 (google collaboration notebook) and 3.11 (local laptop), by installing spacy 2.3.9 and en core web sm 2.3.1.
> 
> While trying to install spacy 2.3.5, it was giving an error of missing wheel file, thanks to this stackexchange article (https://stackoverflow.com/questions/68651829/how-to-install-specific-version-of-spacy), I gave "pip install spacy ~= 2.3.5" (instead of "pip install spacy ==2.3.5").
> 
> Rest of the instructions worked as is from @Quppi 's solution!
> 
> Ps: i must comment: results of resume parsing weren't too great (messed up extracting total experience in all resumes, some names, emails and mobile numbers too were incorrect or missing), so not sure if it really needs spacy 2.3.5 to work better.
> 
> Any way we can install 2.3.5 on latest py versions? Or on which py version can we get spacy 2.3.5 and ecws 2.3.1 working even today?!

This worked very well for me thank you.
Any solution for the accuracy of parsed data?

**Comment by bokkadurgaprasad** [comment]
when i was trying to install spacy i got the below note while installing

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by DurgaPrasad172** [comment]
> when i was trying to install spacy i got the below note while installing
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

I am also facing the same issue

**Comment by bokkadurgaprasad** [comment]
> > when i was trying to install spacy i got the below note while installing
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> I am also facing the same issue

what project are you doing bro? , I have already rectified my issue

**Comment by DurgaPrasad172** [comment]
> > > when i was trying to install spacy i got the below note while installing
> > > note: This error originates from a subprocess, and is likely not a problem with pip.
> > 
> > 
> > I am also facing the same issue
> 
> what project are you doing bro? , I have already rectified my issue

Smart Resume Analyzer

**Comment by naji111** [comment]
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue: `pip install nltk` `pip install spacy==2.3.5` `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz` `pip install pyresparser` does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

thank you brother .. you are amazing

**Comment by DurgaPrasad172** [comment]
Code:
if pdf_file is not None:
            # with st.spinner('Uploading your Resume....'):
            #     time.sleep(4)
            save_image_path = './Uploaded_Resumes/'+pdf_file.name
            with open(save_image_path, "wb") as f:
                f.write(pdf_file.getbuffer())
            show_pdf(save_image_path)
            resume_data = ResumeParser(save_image_path).get_extracted_data()


Error:
  File "C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\util.py", line 714, in load_config
    raise IOError(Errors.E053.format(path=config_path, name="config file"))      
OSError: [E053] Could not read config file from C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyresparser\config.cfg..I have tried all of the above but still i am getting this error..Anyone help me out.

**Comment by DurgaPrasad172** [comment]
> > > when i was trying to install spacy i got the below note while installing
> > > note: This error originates from a subprocess, and is likely not a problem with pip.
> > 
> > 
> > I am also facing the same issue
> 
> what project are you doing bro? , I have already rectified my issue

Code:
if pdf_file is not None:
# with st.spinner('Uploading your Resume....'):
# time.sleep(4)
save_image_path = './Uploaded_Resumes/'+pdf_file.name
with open(save_image_path, "wb") as f:
f.write(pdf_file.getbuffer())
show_pdf(save_image_path)
resume_data = ResumeParser(save_image_path).get_extracted_data()

Error:
File "C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\util.py", line 714, in load_config
raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyresparser\config.cfg..I have tried all of the above but still i am getting this error..Please help me out.

**Comment by DurgaPrasad172** [comment]
> Hey guys, i just figured it out, after being stuck with the same error for a while. It's a version issue: `pip install nltk` `pip install spacy==2.3.5` `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz` `pip install pyresparser` does the trick. Also try different spacy versions and models, because they produce different results. Haven't tested any further myself. Hope this helps :)

Code:
if pdf_file is not None:
# with st.spinner('Uploading your Resume....'):
# time.sleep(4)
save_image_path = './Uploaded_Resumes/'+pdf_file.name
with open(save_image_path, "wb") as f:
f.write(pdf_file.getbuffer())
show_pdf(save_image_path)
resume_data = ResumeParser(save_image_path).get_extracted_data()

Error:
File "C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\util.py", line 714, in load_config
raise IOError(Errors.E053.format(path=config_path, name="config file"))
OSError: [E053] Could not read config file from C:\Users\Durga Prasad\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyresparser\config.cfg..I have tried all of the above but still i am getting this error......................................Still i am getting the same isssue
